name: Deploy Shibe to heroku

on:
  push:
    branches:
      - release
    paths:
      - shibe/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "homework-manager-primary" #Must be unique in Heroku
          heroku_email: "bot.rem.autogenerate@gmail.com"
