# attention: shibe and burritos are on different accounts, be cautious when dealing with heroku tokens
name: Deploy Shibe to heroku

on:
  push:
    paths:
      - packages/shibe/**
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "homework-manager-primary"
          heroku_email: ${{secrets.SHIBE_HEROKU_ACCOUNT_EMAIL}}
